import os

SOCIAL_AUTH_SAML_SP_ENTITY_ID = 'http://saml.yoursite.com'

SOCIAL_AUTH_SAML_SP_PUBLIC_CERT = """MIIDuTCCAqGgAwIBAgIJAJxsv1SRKfL8MA0GCSqGSIb3DQEBCwUAMHMxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQxLDAqBgkqhkiG9w0BCQEWHWhhbmRlcnNvbi5jb250cmVy
YXNAZ21haWwuY29tMB4XDTE1MTAwNTE4MzcwMVoXDTI1MTAwNDE4MzcwMVowczEL
MAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVy
bmV0IFdpZGdpdHMgUHR5IEx0ZDEsMCoGCSqGSIb3DQEJARYdaGFuZGVyc29uLmNv
bnRyZXJhc0BnbWFpbC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQCpbbQ071b6AS/zZ9m/g1Ajl3tV0GakVu55hqC0MYMOC3KW7bCEABBP+3rbwvVm
xN+sIGvAlZwrgai4H8UdlObq3N9HSR64tzsPjGrenOD42iSj/5ZDHzyrqmLJFMvx
nuPiU+eBET4DisWC29W/KZZXE+eAWct4vsB/iC6WXI0YKvz8VTGMLiL5chUHpfir
USHi+ooUDABAehA6ap5dBlQiTwKe1GwM6AiWuIm9m82aam8c+jf8UMrWFpsvprTb
647ESLluDbxyKAgJXmt+rnFiXQ1Y3/LrZCDcdgiCCumn77f8NWo02axRtP5MFIOp
A69c3LgEiNTWG6a5E/c5XMrXAgMBAAGjUDBOMB0GA1UdDgQWBBQDb0iAT9eL2/Fg
OE4lOKUQL/28/TAfBgNVHSMEGDAWgBQDb0iAT9eL2/FgOE4lOKUQL/28/TAMBgNV
HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB+DCphSmOqpfW5jH4TI/T+xyW2
+kLXbasrVqXgI/SzK8wPkP5Y3SBNeIxCYN2txz86tXejpzo3HtQAhyBWRreJXIEb
q5Flqdi6cmiihzYZQJTjtXEuJMB0SS9eg0kwJyZtlO9W4NcQ7NDFJd3QaGNmJUyT
2U2Sca+nfHmt8orJbUX2nJ2ub4aD+4lJKkqVIrOpXUWI09x8UZG/5Cur3/W4zygV
RliL2iRbGYtXnK4AGmb2CeMRi06Ggf8K2LxoqWoOD5J+u9DgSA1iS/To3E+oVbTJ
YdmqUqNEZZvqWGBCfuBsiPOUWRslkvgo4ilEy6NQrDIvgT2Zrpya0zfSyPke"""


SOCIAL_AUTH_SAML_ORG_INFO = {
    "en-US": {
        "name": "Laureate Internation Universities",
        "displayname": "Laureate Inc.",
        "url": "global3.laureate.net",
    }
}


SOCIAL_AUTH_SAML_ENABLED_IDPS = {
    "testshib": {
        "entity_id": "https://idp.testshib.org/idp/shibboleth",
        "url": "https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO",
        "x509cert": "MIIEDjCCAvagAwIBAgIBADA ... 8Bbnl+ev0peYzxFyF5sQA==",
    }
}
